import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "@/components/auth/AuthProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "MovieScope",
  description: "Generated by Movie Scope",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.png" sizes="any" />
      </head>
      <body>
        <div id="root">
          <div className="flex h-full w-full flex-auto flex-col justify-between bg-gray-900">
            <AuthProvider>
              <NavBar />
              {children}
              <Footer />
            </AuthProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
