CREATE EXTENSION IF NOT EXISTS "pgcrypto";

ALTER TABLE "profile" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "profile" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "profile" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
